const GENDERTYPES = ["MALE", "FEMALE", "OTHER"];
const PRIORITY_TYPES = ["CRITICAL", "HIGHEST", "HIGH", "MEDIUM", "LOW"];
const LABEL_TYPES = ["WORK", "EDUCATION", "HOME", "HOBBY"];
const TODO_PENDING_STAGE = "PENDING";
const TODO_STAGES = [
  TODO_PENDING_STAGE,
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
];

module.exports = {
  GENDERTYPES,
  PRIORITY_TYPES,
  LABEL_TYPES,
  TODO_STAGES,
  TODO_PENDING_STAGE,
};
